name: Deploy Python project to Azure Function App

on:
  push:
    branches: ["main"]
    paths:
      - 'AzureAPI/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'ton-nom-app-azure'   # REMPLACE par le vrai nom de ton Azure Function App
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './AzureAPI'  # Le chemin vers le dossier de l'API
  PYTHON_VERSION: '3.12'                        # La version de Python utilisée

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      with:
        lfs: true # Indispensable pour télécharger tes gros fichiers modèles (Numpy/Pickle) depuis Git LFS

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
